CREATE BUFFERPOOL "FEELVIEW_BF_IDX1"  SIZE 10000 PAGESIZE 8K;
CREATE BUFFERPOOL "FEELVIEW_BF_TAB1"  SIZE 30000 PAGESIZE 8K;
update db cfg using logfilsiz 2000;
update db cfg using logprimary 25;
update db cfg using logsecond 50;
CREATE TABLESPACE FEELVIEW_DATA PAGESIZE 8K MANAGED BY DATABASE USING(FILE '/home/feelview/feelview/FEELVIEW_DATA' 4096 M) EXTENTSIZE 32 OVERHEAD 10.5 PREFETCHSIZE 32 TRANSFERRATE 0.14 BUFFERPOOL FEELVIEW_BF_TAB1;
CREATE TABLESPACE FEELVIEW_INDEX PAGESIZE 8K  MANAGED BY DATABASE USING (FILE '/home/feelview/feelview/FEELVIEW_INDEX' 1024 M)  EXTENTSIZE 32 OVERHEAD 10.5 PREFETCHSIZE 32 TRANSFERRATE 0.14 BUFFERPOOL  FEELVIEW_BF_IDX1;
CREATE SYSTEM temporary TABLESPACE FEELVIEW_TEMP PAGESIZE 8K  MANAGED BY SYSTEM USING ('/home/feelview/feelview/tempspace/FEELVIEW_TEMP') EXTENTSIZE 32 OVERHEAD 10.5 PREFETCHSIZE 32 TRANSFERRATE 0.14 BUFFERPOOL FEELVIEW_BF_TAB1;
CREATE SCHEMA "FEELVIEW" AUTHORIZATION "FEELVIEW";