--TRIG_CML_SENT_INFOS_HIS_0101
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0101 BEFORE
insert ON CML_SENT_INFOS_HIS_0101 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0101.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0102
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0102 BEFORE
insert ON CML_SENT_INFOS_HIS_0102 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0102.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0103
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0103 BEFORE
insert ON CML_SENT_INFOS_HIS_0103 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0103.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0104
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0104 BEFORE
insert ON CML_SENT_INFOS_HIS_0104 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0104.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0105
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0105 BEFORE
insert ON CML_SENT_INFOS_HIS_0105 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0105.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0106
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0106 BEFORE
insert ON CML_SENT_INFOS_HIS_0106 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0106.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0107
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0107 BEFORE
insert ON CML_SENT_INFOS_HIS_0107 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0107.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0108
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0108 BEFORE
insert ON CML_SENT_INFOS_HIS_0108 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0108.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0109
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0109 BEFORE
insert ON CML_SENT_INFOS_HIS_0109 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0109.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0110
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0110 BEFORE
insert ON CML_SENT_INFOS_HIS_0110 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0110.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0111
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0111 BEFORE
insert ON CML_SENT_INFOS_HIS_0111 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0111.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0112
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0112 BEFORE
insert ON CML_SENT_INFOS_HIS_0112 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0112.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0113
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0113 BEFORE
insert ON CML_SENT_INFOS_HIS_0113 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0113.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0114
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0114 BEFORE
insert ON CML_SENT_INFOS_HIS_0114 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0114.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0115
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0115 BEFORE
insert ON CML_SENT_INFOS_HIS_0115 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0115.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0116
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0116 BEFORE
insert ON CML_SENT_INFOS_HIS_0116 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0116.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0117
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0117 BEFORE
insert ON CML_SENT_INFOS_HIS_0117 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0117.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0118
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0118 BEFORE
insert ON CML_SENT_INFOS_HIS_0118 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0118.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0119
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0119 BEFORE
insert ON CML_SENT_INFOS_HIS_0119 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0119.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0120
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0120 BEFORE
insert ON CML_SENT_INFOS_HIS_0120 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0120.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0121
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0121 BEFORE
insert ON CML_SENT_INFOS_HIS_0121 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0121.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0122
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0122 BEFORE
insert ON CML_SENT_INFOS_HIS_0122 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0122.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0123
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0123 BEFORE
insert ON CML_SENT_INFOS_HIS_0123 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0123.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0124
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0124 BEFORE
insert ON CML_SENT_INFOS_HIS_0124 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0124.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0125
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0125 BEFORE
insert ON CML_SENT_INFOS_HIS_0125 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0125.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0126
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0126 BEFORE
insert ON CML_SENT_INFOS_HIS_0126 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0126.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0127
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0127 BEFORE
insert ON CML_SENT_INFOS_HIS_0127 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0127.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0128
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0128 BEFORE
insert ON CML_SENT_INFOS_HIS_0128 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0128.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0129
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0129 BEFORE
insert ON CML_SENT_INFOS_HIS_0129 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0129.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0130
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0130 BEFORE
insert ON CML_SENT_INFOS_HIS_0130 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0130.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0131
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0131 BEFORE
insert ON CML_SENT_INFOS_HIS_0131 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0131.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0201
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0201 BEFORE
insert ON CML_SENT_INFOS_HIS_0201 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0201.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0202
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0202 BEFORE
insert ON CML_SENT_INFOS_HIS_0202 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0202.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0203
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0203 BEFORE
insert ON CML_SENT_INFOS_HIS_0203 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0203.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0204
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0204 BEFORE
insert ON CML_SENT_INFOS_HIS_0204 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0204.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0205
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0205 BEFORE
insert ON CML_SENT_INFOS_HIS_0205 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0205.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0206
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0206 BEFORE
insert ON CML_SENT_INFOS_HIS_0206 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0206.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0207
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0207 BEFORE
insert ON CML_SENT_INFOS_HIS_0207 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0207.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0208
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0208 BEFORE
insert ON CML_SENT_INFOS_HIS_0208 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0208.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0209
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0209 BEFORE
insert ON CML_SENT_INFOS_HIS_0209 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0209.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0210
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0210 BEFORE
insert ON CML_SENT_INFOS_HIS_0210 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0210.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0211
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0211 BEFORE
insert ON CML_SENT_INFOS_HIS_0211 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0211.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0212
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0212 BEFORE
insert ON CML_SENT_INFOS_HIS_0212 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0212.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0213
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0213 BEFORE
insert ON CML_SENT_INFOS_HIS_0213 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0213.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0214
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0214 BEFORE
insert ON CML_SENT_INFOS_HIS_0214 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0214.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0215
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0215 BEFORE
insert ON CML_SENT_INFOS_HIS_0215 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0215.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0216
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0216 BEFORE
insert ON CML_SENT_INFOS_HIS_0216 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0216.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0217
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0217 BEFORE
insert ON CML_SENT_INFOS_HIS_0217 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0217.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0218
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0218 BEFORE
insert ON CML_SENT_INFOS_HIS_0218 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0218.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0219
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0219 BEFORE
insert ON CML_SENT_INFOS_HIS_0219 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0219.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0220
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0220 BEFORE
insert ON CML_SENT_INFOS_HIS_0220 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0220.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0221
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0221 BEFORE
insert ON CML_SENT_INFOS_HIS_0221 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0221.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0222
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0222 BEFORE
insert ON CML_SENT_INFOS_HIS_0222 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0222.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0223
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0223 BEFORE
insert ON CML_SENT_INFOS_HIS_0223 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0223.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0224
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0224 BEFORE
insert ON CML_SENT_INFOS_HIS_0224 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0224.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0225
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0225 BEFORE
insert ON CML_SENT_INFOS_HIS_0225 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0225.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0226
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0226 BEFORE
insert ON CML_SENT_INFOS_HIS_0226 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0226.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0227
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0227 BEFORE
insert ON CML_SENT_INFOS_HIS_0227 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0227.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0228
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0228 BEFORE
insert ON CML_SENT_INFOS_HIS_0228 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0228.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0229
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0229 BEFORE
insert ON CML_SENT_INFOS_HIS_0229 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0229.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0301
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0301 BEFORE
insert ON CML_SENT_INFOS_HIS_0301 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0301.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0302
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0302 BEFORE
insert ON CML_SENT_INFOS_HIS_0302 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0302.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0303
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0303 BEFORE
insert ON CML_SENT_INFOS_HIS_0303 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0303.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0304
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0304 BEFORE
insert ON CML_SENT_INFOS_HIS_0304 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0304.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0305
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0305 BEFORE
insert ON CML_SENT_INFOS_HIS_0305 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0305.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0306
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0306 BEFORE
insert ON CML_SENT_INFOS_HIS_0306 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0306.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0307
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0307 BEFORE
insert ON CML_SENT_INFOS_HIS_0307 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0307.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0308
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0308 BEFORE
insert ON CML_SENT_INFOS_HIS_0308 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0308.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0309
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0309 BEFORE
insert ON CML_SENT_INFOS_HIS_0309 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0309.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0310
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0310 BEFORE
insert ON CML_SENT_INFOS_HIS_0310 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0310.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0311
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0311 BEFORE
insert ON CML_SENT_INFOS_HIS_0311 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0311.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0312
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0312 BEFORE
insert ON CML_SENT_INFOS_HIS_0312 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0312.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0313
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0313 BEFORE
insert ON CML_SENT_INFOS_HIS_0313 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0313.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0314
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0314 BEFORE
insert ON CML_SENT_INFOS_HIS_0314 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0314.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0315
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0315 BEFORE
insert ON CML_SENT_INFOS_HIS_0315 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0315.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0316
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0316 BEFORE
insert ON CML_SENT_INFOS_HIS_0316 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0316.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0317
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0317 BEFORE
insert ON CML_SENT_INFOS_HIS_0317 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0317.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0318
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0318 BEFORE
insert ON CML_SENT_INFOS_HIS_0318 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0318.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0319
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0319 BEFORE
insert ON CML_SENT_INFOS_HIS_0319 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0319.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0320
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0320 BEFORE
insert ON CML_SENT_INFOS_HIS_0320 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0320.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0321
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0321 BEFORE
insert ON CML_SENT_INFOS_HIS_0321 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0321.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0322
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0322 BEFORE
insert ON CML_SENT_INFOS_HIS_0322 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0322.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0323
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0323 BEFORE
insert ON CML_SENT_INFOS_HIS_0323 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0323.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0324
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0324 BEFORE
insert ON CML_SENT_INFOS_HIS_0324 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0324.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0325
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0325 BEFORE
insert ON CML_SENT_INFOS_HIS_0325 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0325.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0326
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0326 BEFORE
insert ON CML_SENT_INFOS_HIS_0326 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0326.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0327
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0327 BEFORE
insert ON CML_SENT_INFOS_HIS_0327 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0327.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0328
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0328 BEFORE
insert ON CML_SENT_INFOS_HIS_0328 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0328.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0329
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0329 BEFORE
insert ON CML_SENT_INFOS_HIS_0329 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0329.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0330
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0330 BEFORE
insert ON CML_SENT_INFOS_HIS_0330 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0330.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0331
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0331 BEFORE
insert ON CML_SENT_INFOS_HIS_0331 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0331.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0401
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0401 BEFORE
insert ON CML_SENT_INFOS_HIS_0401 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0401.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0402
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0402 BEFORE
insert ON CML_SENT_INFOS_HIS_0402 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0402.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0403
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0403 BEFORE
insert ON CML_SENT_INFOS_HIS_0403 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0403.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0404
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0404 BEFORE
insert ON CML_SENT_INFOS_HIS_0404 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0404.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0405
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0405 BEFORE
insert ON CML_SENT_INFOS_HIS_0405 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0405.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0406
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0406 BEFORE
insert ON CML_SENT_INFOS_HIS_0406 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0406.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0407
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0407 BEFORE
insert ON CML_SENT_INFOS_HIS_0407 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0407.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0408
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0408 BEFORE
insert ON CML_SENT_INFOS_HIS_0408 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0408.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0409
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0409 BEFORE
insert ON CML_SENT_INFOS_HIS_0409 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0409.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0410
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0410 BEFORE
insert ON CML_SENT_INFOS_HIS_0410 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0410.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0411
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0411 BEFORE
insert ON CML_SENT_INFOS_HIS_0411 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0411.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0412
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0412 BEFORE
insert ON CML_SENT_INFOS_HIS_0412 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0412.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0413
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0413 BEFORE
insert ON CML_SENT_INFOS_HIS_0413 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0413.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0414
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0414 BEFORE
insert ON CML_SENT_INFOS_HIS_0414 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0414.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0415
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0415 BEFORE
insert ON CML_SENT_INFOS_HIS_0415 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0415.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0416
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0416 BEFORE
insert ON CML_SENT_INFOS_HIS_0416 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0416.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0417
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0417 BEFORE
insert ON CML_SENT_INFOS_HIS_0417 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0417.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0418
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0418 BEFORE
insert ON CML_SENT_INFOS_HIS_0418 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0418.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0419
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0419 BEFORE
insert ON CML_SENT_INFOS_HIS_0419 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0419.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0420
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0420 BEFORE
insert ON CML_SENT_INFOS_HIS_0420 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0420.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0421
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0421 BEFORE
insert ON CML_SENT_INFOS_HIS_0421 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0421.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0422
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0422 BEFORE
insert ON CML_SENT_INFOS_HIS_0422 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0422.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0423
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0423 BEFORE
insert ON CML_SENT_INFOS_HIS_0423 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0423.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0424
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0424 BEFORE
insert ON CML_SENT_INFOS_HIS_0424 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0424.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0425
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0425 BEFORE
insert ON CML_SENT_INFOS_HIS_0425 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0425.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0426
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0426 BEFORE
insert ON CML_SENT_INFOS_HIS_0426 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0426.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0427
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0427 BEFORE
insert ON CML_SENT_INFOS_HIS_0427 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0427.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0428
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0428 BEFORE
insert ON CML_SENT_INFOS_HIS_0428 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0428.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0429
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0429 BEFORE
insert ON CML_SENT_INFOS_HIS_0429 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0429.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0430
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0430 BEFORE
insert ON CML_SENT_INFOS_HIS_0430 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0430.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0501
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0501 BEFORE
insert ON CML_SENT_INFOS_HIS_0501 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0501.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0502
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0502 BEFORE
insert ON CML_SENT_INFOS_HIS_0502 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0502.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0503
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0503 BEFORE
insert ON CML_SENT_INFOS_HIS_0503 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0503.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0504
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0504 BEFORE
insert ON CML_SENT_INFOS_HIS_0504 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0504.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0505
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0505 BEFORE
insert ON CML_SENT_INFOS_HIS_0505 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0505.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0506
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0506 BEFORE
insert ON CML_SENT_INFOS_HIS_0506 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0506.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0507
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0507 BEFORE
insert ON CML_SENT_INFOS_HIS_0507 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0507.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0508
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0508 BEFORE
insert ON CML_SENT_INFOS_HIS_0508 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0508.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0509
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0509 BEFORE
insert ON CML_SENT_INFOS_HIS_0509 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0509.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0510
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0510 BEFORE
insert ON CML_SENT_INFOS_HIS_0510 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0510.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0511
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0511 BEFORE
insert ON CML_SENT_INFOS_HIS_0511 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0511.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0512
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0512 BEFORE
insert ON CML_SENT_INFOS_HIS_0512 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0512.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0513
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0513 BEFORE
insert ON CML_SENT_INFOS_HIS_0513 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0513.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0514
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0514 BEFORE
insert ON CML_SENT_INFOS_HIS_0514 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0514.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0515
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0515 BEFORE
insert ON CML_SENT_INFOS_HIS_0515 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0515.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0516
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0516 BEFORE
insert ON CML_SENT_INFOS_HIS_0516 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0516.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0517
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0517 BEFORE
insert ON CML_SENT_INFOS_HIS_0517 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0517.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0518
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0518 BEFORE
insert ON CML_SENT_INFOS_HIS_0518 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0518.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0519
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0519 BEFORE
insert ON CML_SENT_INFOS_HIS_0519 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0519.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0520
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0520 BEFORE
insert ON CML_SENT_INFOS_HIS_0520 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0520.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0521
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0521 BEFORE
insert ON CML_SENT_INFOS_HIS_0521 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0521.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0522
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0522 BEFORE
insert ON CML_SENT_INFOS_HIS_0522 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0522.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0523
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0523 BEFORE
insert ON CML_SENT_INFOS_HIS_0523 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0523.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0524
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0524 BEFORE
insert ON CML_SENT_INFOS_HIS_0524 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0524.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0525
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0525 BEFORE
insert ON CML_SENT_INFOS_HIS_0525 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0525.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0526
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0526 BEFORE
insert ON CML_SENT_INFOS_HIS_0526 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0526.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0527
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0527 BEFORE
insert ON CML_SENT_INFOS_HIS_0527 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0527.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0528
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0528 BEFORE
insert ON CML_SENT_INFOS_HIS_0528 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0528.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0529
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0529 BEFORE
insert ON CML_SENT_INFOS_HIS_0529 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0529.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0530
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0530 BEFORE
insert ON CML_SENT_INFOS_HIS_0530 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0530.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0531
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0531 BEFORE
insert ON CML_SENT_INFOS_HIS_0531 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0531.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0601
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0601 BEFORE
insert ON CML_SENT_INFOS_HIS_0601 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0601.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0602
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0602 BEFORE
insert ON CML_SENT_INFOS_HIS_0602 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0602.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0603
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0603 BEFORE
insert ON CML_SENT_INFOS_HIS_0603 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0603.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0604
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0604 BEFORE
insert ON CML_SENT_INFOS_HIS_0604 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0604.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0605
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0605 BEFORE
insert ON CML_SENT_INFOS_HIS_0605 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0605.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0606
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0606 BEFORE
insert ON CML_SENT_INFOS_HIS_0606 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0606.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0607
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0607 BEFORE
insert ON CML_SENT_INFOS_HIS_0607 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0607.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0608
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0608 BEFORE
insert ON CML_SENT_INFOS_HIS_0608 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0608.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0609
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0609 BEFORE
insert ON CML_SENT_INFOS_HIS_0609 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0609.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0610
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0610 BEFORE
insert ON CML_SENT_INFOS_HIS_0610 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0610.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0611
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0611 BEFORE
insert ON CML_SENT_INFOS_HIS_0611 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0611.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0612
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0612 BEFORE
insert ON CML_SENT_INFOS_HIS_0612 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0612.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0613
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0613 BEFORE
insert ON CML_SENT_INFOS_HIS_0613 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0613.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0614
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0614 BEFORE
insert ON CML_SENT_INFOS_HIS_0614 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0614.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0615
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0615 BEFORE
insert ON CML_SENT_INFOS_HIS_0615 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0615.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0616
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0616 BEFORE
insert ON CML_SENT_INFOS_HIS_0616 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0616.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0617
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0617 BEFORE
insert ON CML_SENT_INFOS_HIS_0617 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0617.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0618
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0618 BEFORE
insert ON CML_SENT_INFOS_HIS_0618 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0618.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0619
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0619 BEFORE
insert ON CML_SENT_INFOS_HIS_0619 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0619.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0620
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0620 BEFORE
insert ON CML_SENT_INFOS_HIS_0620 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0620.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0621
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0621 BEFORE
insert ON CML_SENT_INFOS_HIS_0621 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0621.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0622
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0622 BEFORE
insert ON CML_SENT_INFOS_HIS_0622 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0622.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0623
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0623 BEFORE
insert ON CML_SENT_INFOS_HIS_0623 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0623.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0624
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0624 BEFORE
insert ON CML_SENT_INFOS_HIS_0624 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0624.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0625
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0625 BEFORE
insert ON CML_SENT_INFOS_HIS_0625 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0625.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0626
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0626 BEFORE
insert ON CML_SENT_INFOS_HIS_0626 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0626.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0627
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0627 BEFORE
insert ON CML_SENT_INFOS_HIS_0627 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0627.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0628
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0628 BEFORE
insert ON CML_SENT_INFOS_HIS_0628 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0628.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0629
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0629 BEFORE
insert ON CML_SENT_INFOS_HIS_0629 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0629.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0630
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0630 BEFORE
insert ON CML_SENT_INFOS_HIS_0630 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0630.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0701
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0701 BEFORE
insert ON CML_SENT_INFOS_HIS_0701 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0701.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0702
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0702 BEFORE
insert ON CML_SENT_INFOS_HIS_0702 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0702.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0703
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0703 BEFORE
insert ON CML_SENT_INFOS_HIS_0703 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0703.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0704
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0704 BEFORE
insert ON CML_SENT_INFOS_HIS_0704 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0704.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0705
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0705 BEFORE
insert ON CML_SENT_INFOS_HIS_0705 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0705.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0706
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0706 BEFORE
insert ON CML_SENT_INFOS_HIS_0706 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0706.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0707
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0707 BEFORE
insert ON CML_SENT_INFOS_HIS_0707 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0707.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0708
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0708 BEFORE
insert ON CML_SENT_INFOS_HIS_0708 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0708.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0709
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0709 BEFORE
insert ON CML_SENT_INFOS_HIS_0709 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0709.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0710
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0710 BEFORE
insert ON CML_SENT_INFOS_HIS_0710 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0710.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0711
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0711 BEFORE
insert ON CML_SENT_INFOS_HIS_0711 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0711.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0712
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0712 BEFORE
insert ON CML_SENT_INFOS_HIS_0712 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0712.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0713
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0713 BEFORE
insert ON CML_SENT_INFOS_HIS_0713 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0713.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0714
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0714 BEFORE
insert ON CML_SENT_INFOS_HIS_0714 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0714.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0715
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0715 BEFORE
insert ON CML_SENT_INFOS_HIS_0715 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0715.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0716
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0716 BEFORE
insert ON CML_SENT_INFOS_HIS_0716 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0716.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0717
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0717 BEFORE
insert ON CML_SENT_INFOS_HIS_0717 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0717.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0718
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0718 BEFORE
insert ON CML_SENT_INFOS_HIS_0718 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0718.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0719
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0719 BEFORE
insert ON CML_SENT_INFOS_HIS_0719 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0719.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0720
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0720 BEFORE
insert ON CML_SENT_INFOS_HIS_0720 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0720.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0721
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0721 BEFORE
insert ON CML_SENT_INFOS_HIS_0721 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0721.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0722
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0722 BEFORE
insert ON CML_SENT_INFOS_HIS_0722 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0722.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0723
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0723 BEFORE
insert ON CML_SENT_INFOS_HIS_0723 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0723.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0724
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0724 BEFORE
insert ON CML_SENT_INFOS_HIS_0724 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0724.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0725
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0725 BEFORE
insert ON CML_SENT_INFOS_HIS_0725 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0725.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0726
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0726 BEFORE
insert ON CML_SENT_INFOS_HIS_0726 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0726.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0727
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0727 BEFORE
insert ON CML_SENT_INFOS_HIS_0727 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0727.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0728
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0728 BEFORE
insert ON CML_SENT_INFOS_HIS_0728 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0728.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0729
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0729 BEFORE
insert ON CML_SENT_INFOS_HIS_0729 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0729.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0730
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0730 BEFORE
insert ON CML_SENT_INFOS_HIS_0730 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0730.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0731
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0731 BEFORE
insert ON CML_SENT_INFOS_HIS_0731 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0731.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0801
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0801 BEFORE
insert ON CML_SENT_INFOS_HIS_0801 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0801.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0802
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0802 BEFORE
insert ON CML_SENT_INFOS_HIS_0802 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0802.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0803
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0803 BEFORE
insert ON CML_SENT_INFOS_HIS_0803 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0803.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0804
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0804 BEFORE
insert ON CML_SENT_INFOS_HIS_0804 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0804.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0805
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0805 BEFORE
insert ON CML_SENT_INFOS_HIS_0805 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0805.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0806
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0806 BEFORE
insert ON CML_SENT_INFOS_HIS_0806 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0806.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0807
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0807 BEFORE
insert ON CML_SENT_INFOS_HIS_0807 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0807.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0808
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0808 BEFORE
insert ON CML_SENT_INFOS_HIS_0808 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0808.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0809
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0809 BEFORE
insert ON CML_SENT_INFOS_HIS_0809 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0809.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0810
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0810 BEFORE
insert ON CML_SENT_INFOS_HIS_0810 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0810.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0811
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0811 BEFORE
insert ON CML_SENT_INFOS_HIS_0811 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0811.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0812
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0812 BEFORE
insert ON CML_SENT_INFOS_HIS_0812 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0812.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0813
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0813 BEFORE
insert ON CML_SENT_INFOS_HIS_0813 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0813.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0814
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0814 BEFORE
insert ON CML_SENT_INFOS_HIS_0814 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0814.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0815
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0815 BEFORE
insert ON CML_SENT_INFOS_HIS_0815 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0815.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0816
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0816 BEFORE
insert ON CML_SENT_INFOS_HIS_0816 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0816.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0817
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0817 BEFORE
insert ON CML_SENT_INFOS_HIS_0817 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0817.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0818
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0818 BEFORE
insert ON CML_SENT_INFOS_HIS_0818 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0818.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0819
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0819 BEFORE
insert ON CML_SENT_INFOS_HIS_0819 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0819.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0820
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0820 BEFORE
insert ON CML_SENT_INFOS_HIS_0820 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0820.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0821
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0821 BEFORE
insert ON CML_SENT_INFOS_HIS_0821 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0821.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0822
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0822 BEFORE
insert ON CML_SENT_INFOS_HIS_0822 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0822.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0823
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0823 BEFORE
insert ON CML_SENT_INFOS_HIS_0823 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0823.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0824
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0824 BEFORE
insert ON CML_SENT_INFOS_HIS_0824 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0824.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0825
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0825 BEFORE
insert ON CML_SENT_INFOS_HIS_0825 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0825.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0826
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0826 BEFORE
insert ON CML_SENT_INFOS_HIS_0826 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0826.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0827
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0827 BEFORE
insert ON CML_SENT_INFOS_HIS_0827 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0827.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0828
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0828 BEFORE
insert ON CML_SENT_INFOS_HIS_0828 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0828.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0829
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0829 BEFORE
insert ON CML_SENT_INFOS_HIS_0829 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0829.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0830
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0830 BEFORE
insert ON CML_SENT_INFOS_HIS_0830 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0830.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0831
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0831 BEFORE
insert ON CML_SENT_INFOS_HIS_0831 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0831.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0901
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0901 BEFORE
insert ON CML_SENT_INFOS_HIS_0901 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0901.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0902
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0902 BEFORE
insert ON CML_SENT_INFOS_HIS_0902 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0902.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0903
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0903 BEFORE
insert ON CML_SENT_INFOS_HIS_0903 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0903.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0904
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0904 BEFORE
insert ON CML_SENT_INFOS_HIS_0904 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0904.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0905
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0905 BEFORE
insert ON CML_SENT_INFOS_HIS_0905 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0905.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0906
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0906 BEFORE
insert ON CML_SENT_INFOS_HIS_0906 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0906.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0907
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0907 BEFORE
insert ON CML_SENT_INFOS_HIS_0907 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0907.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0908
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0908 BEFORE
insert ON CML_SENT_INFOS_HIS_0908 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0908.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0909
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0909 BEFORE
insert ON CML_SENT_INFOS_HIS_0909 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0909.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0910
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0910 BEFORE
insert ON CML_SENT_INFOS_HIS_0910 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0910.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0911
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0911 BEFORE
insert ON CML_SENT_INFOS_HIS_0911 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0911.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0912
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0912 BEFORE
insert ON CML_SENT_INFOS_HIS_0912 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0912.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0913
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0913 BEFORE
insert ON CML_SENT_INFOS_HIS_0913 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0913.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0914
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0914 BEFORE
insert ON CML_SENT_INFOS_HIS_0914 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0914.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0915
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0915 BEFORE
insert ON CML_SENT_INFOS_HIS_0915 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0915.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0916
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0916 BEFORE
insert ON CML_SENT_INFOS_HIS_0916 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0916.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0917
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0917 BEFORE
insert ON CML_SENT_INFOS_HIS_0917 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0917.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0918
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0918 BEFORE
insert ON CML_SENT_INFOS_HIS_0918 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0918.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0919
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0919 BEFORE
insert ON CML_SENT_INFOS_HIS_0919 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0919.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0920
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0920 BEFORE
insert ON CML_SENT_INFOS_HIS_0920 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0920.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0921
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0921 BEFORE
insert ON CML_SENT_INFOS_HIS_0921 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0921.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0922
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0922 BEFORE
insert ON CML_SENT_INFOS_HIS_0922 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0922.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0923
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0923 BEFORE
insert ON CML_SENT_INFOS_HIS_0923 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0923.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0924
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0924 BEFORE
insert ON CML_SENT_INFOS_HIS_0924 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0924.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0925
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0925 BEFORE
insert ON CML_SENT_INFOS_HIS_0925 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0925.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0926
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0926 BEFORE
insert ON CML_SENT_INFOS_HIS_0926 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0926.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0927
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0927 BEFORE
insert ON CML_SENT_INFOS_HIS_0927 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0927.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0928
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0928 BEFORE
insert ON CML_SENT_INFOS_HIS_0928 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0928.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0929
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0929 BEFORE
insert ON CML_SENT_INFOS_HIS_0929 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0929.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_0930
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_0930 BEFORE
insert ON CML_SENT_INFOS_HIS_0930 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_0930.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1001
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1001 BEFORE
insert ON CML_SENT_INFOS_HIS_1001 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1001.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1002
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1002 BEFORE
insert ON CML_SENT_INFOS_HIS_1002 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1002.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1003
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1003 BEFORE
insert ON CML_SENT_INFOS_HIS_1003 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1003.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1004
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1004 BEFORE
insert ON CML_SENT_INFOS_HIS_1004 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1004.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1005
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1005 BEFORE
insert ON CML_SENT_INFOS_HIS_1005 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1005.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1006
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1006 BEFORE
insert ON CML_SENT_INFOS_HIS_1006 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1006.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1007
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1007 BEFORE
insert ON CML_SENT_INFOS_HIS_1007 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1007.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1008
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1008 BEFORE
insert ON CML_SENT_INFOS_HIS_1008 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1008.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1009
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1009 BEFORE
insert ON CML_SENT_INFOS_HIS_1009 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1009.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1010
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1010 BEFORE
insert ON CML_SENT_INFOS_HIS_1010 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1010.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1011
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1011 BEFORE
insert ON CML_SENT_INFOS_HIS_1011 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1011.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1012
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1012 BEFORE
insert ON CML_SENT_INFOS_HIS_1012 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1012.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1013
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1013 BEFORE
insert ON CML_SENT_INFOS_HIS_1013 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1013.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1014
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1014 BEFORE
insert ON CML_SENT_INFOS_HIS_1014 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1014.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1015
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1015 BEFORE
insert ON CML_SENT_INFOS_HIS_1015 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1015.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1016
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1016 BEFORE
insert ON CML_SENT_INFOS_HIS_1016 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1016.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1017
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1017 BEFORE
insert ON CML_SENT_INFOS_HIS_1017 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1017.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1018
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1018 BEFORE
insert ON CML_SENT_INFOS_HIS_1018 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1018.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1019
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1019 BEFORE
insert ON CML_SENT_INFOS_HIS_1019 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1019.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1020
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1020 BEFORE
insert ON CML_SENT_INFOS_HIS_1020 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1020.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1021
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1021 BEFORE
insert ON CML_SENT_INFOS_HIS_1021 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1021.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1022
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1022 BEFORE
insert ON CML_SENT_INFOS_HIS_1022 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1022.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1023
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1023 BEFORE
insert ON CML_SENT_INFOS_HIS_1023 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1023.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1024
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1024 BEFORE
insert ON CML_SENT_INFOS_HIS_1024 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1024.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1025
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1025 BEFORE
insert ON CML_SENT_INFOS_HIS_1025 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1025.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1026
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1026 BEFORE
insert ON CML_SENT_INFOS_HIS_1026 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1026.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1027
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1027 BEFORE
insert ON CML_SENT_INFOS_HIS_1027 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1027.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1028
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1028 BEFORE
insert ON CML_SENT_INFOS_HIS_1028 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1028.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1029
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1029 BEFORE
insert ON CML_SENT_INFOS_HIS_1029 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1029.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1030
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1030 BEFORE
insert ON CML_SENT_INFOS_HIS_1030 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1030.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1031
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1031 BEFORE
insert ON CML_SENT_INFOS_HIS_1031 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1031.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1101
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1101 BEFORE
insert ON CML_SENT_INFOS_HIS_1101 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1101.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1102
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1102 BEFORE
insert ON CML_SENT_INFOS_HIS_1102 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1102.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1103
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1103 BEFORE
insert ON CML_SENT_INFOS_HIS_1103 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1103.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1104
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1104 BEFORE
insert ON CML_SENT_INFOS_HIS_1104 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1104.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1105
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1105 BEFORE
insert ON CML_SENT_INFOS_HIS_1105 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1105.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1106
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1106 BEFORE
insert ON CML_SENT_INFOS_HIS_1106 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1106.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1107
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1107 BEFORE
insert ON CML_SENT_INFOS_HIS_1107 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1107.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1108
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1108 BEFORE
insert ON CML_SENT_INFOS_HIS_1108 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1108.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1109
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1109 BEFORE
insert ON CML_SENT_INFOS_HIS_1109 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1109.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1110
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1110 BEFORE
insert ON CML_SENT_INFOS_HIS_1110 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1110.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1111
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1111 BEFORE
insert ON CML_SENT_INFOS_HIS_1111 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1111.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1112
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1112 BEFORE
insert ON CML_SENT_INFOS_HIS_1112 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1112.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1113
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1113 BEFORE
insert ON CML_SENT_INFOS_HIS_1113 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1113.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1114
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1114 BEFORE
insert ON CML_SENT_INFOS_HIS_1114 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1114.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1115
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1115 BEFORE
insert ON CML_SENT_INFOS_HIS_1115 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1115.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1116
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1116 BEFORE
insert ON CML_SENT_INFOS_HIS_1116 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1116.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1117
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1117 BEFORE
insert ON CML_SENT_INFOS_HIS_1117 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1117.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1118
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1118 BEFORE
insert ON CML_SENT_INFOS_HIS_1118 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1118.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1119
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1119 BEFORE
insert ON CML_SENT_INFOS_HIS_1119 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1119.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1120
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1120 BEFORE
insert ON CML_SENT_INFOS_HIS_1120 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1120.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1121
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1121 BEFORE
insert ON CML_SENT_INFOS_HIS_1121 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1121.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1122
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1122 BEFORE
insert ON CML_SENT_INFOS_HIS_1122 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1122.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1123
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1123 BEFORE
insert ON CML_SENT_INFOS_HIS_1123 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1123.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1124
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1124 BEFORE
insert ON CML_SENT_INFOS_HIS_1124 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1124.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1125
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1125 BEFORE
insert ON CML_SENT_INFOS_HIS_1125 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1125.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1126
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1126 BEFORE
insert ON CML_SENT_INFOS_HIS_1126 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1126.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1127
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1127 BEFORE
insert ON CML_SENT_INFOS_HIS_1127 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1127.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1128
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1128 BEFORE
insert ON CML_SENT_INFOS_HIS_1128 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1128.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1129
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1129 BEFORE
insert ON CML_SENT_INFOS_HIS_1129 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1129.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1130
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1130 BEFORE
insert ON CML_SENT_INFOS_HIS_1130 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1130.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1201
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1201 BEFORE
insert ON CML_SENT_INFOS_HIS_1201 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1201.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1202
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1202 BEFORE
insert ON CML_SENT_INFOS_HIS_1202 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1202.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1203
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1203 BEFORE
insert ON CML_SENT_INFOS_HIS_1203 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1203.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1204
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1204 BEFORE
insert ON CML_SENT_INFOS_HIS_1204 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1204.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1205
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1205 BEFORE
insert ON CML_SENT_INFOS_HIS_1205 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1205.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1206
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1206 BEFORE
insert ON CML_SENT_INFOS_HIS_1206 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1206.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1207
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1207 BEFORE
insert ON CML_SENT_INFOS_HIS_1207 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1207.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1208
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1208 BEFORE
insert ON CML_SENT_INFOS_HIS_1208 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1208.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1209
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1209 BEFORE
insert ON CML_SENT_INFOS_HIS_1209 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1209.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1210
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1210 BEFORE
insert ON CML_SENT_INFOS_HIS_1210 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1210.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1211
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1211 BEFORE
insert ON CML_SENT_INFOS_HIS_1211 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1211.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1212
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1212 BEFORE
insert ON CML_SENT_INFOS_HIS_1212 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1212.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1213
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1213 BEFORE
insert ON CML_SENT_INFOS_HIS_1213 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1213.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1214
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1214 BEFORE
insert ON CML_SENT_INFOS_HIS_1214 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1214.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1215
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1215 BEFORE
insert ON CML_SENT_INFOS_HIS_1215 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1215.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1216
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1216 BEFORE
insert ON CML_SENT_INFOS_HIS_1216 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1216.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1217
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1217 BEFORE
insert ON CML_SENT_INFOS_HIS_1217 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1217.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1218
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1218 BEFORE
insert ON CML_SENT_INFOS_HIS_1218 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1218.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1219
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1219 BEFORE
insert ON CML_SENT_INFOS_HIS_1219 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1219.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1220
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1220 BEFORE
insert ON CML_SENT_INFOS_HIS_1220 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1220.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1221
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1221 BEFORE
insert ON CML_SENT_INFOS_HIS_1221 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1221.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1222
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1222 BEFORE
insert ON CML_SENT_INFOS_HIS_1222 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1222.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1223
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1223 BEFORE
insert ON CML_SENT_INFOS_HIS_1223 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1223.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1224
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1224 BEFORE
insert ON CML_SENT_INFOS_HIS_1224 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1224.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1225
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1225 BEFORE
insert ON CML_SENT_INFOS_HIS_1225 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1225.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1226
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1226 BEFORE
insert ON CML_SENT_INFOS_HIS_1226 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1226.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1227
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1227 BEFORE
insert ON CML_SENT_INFOS_HIS_1227 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1227.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1228
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1228 BEFORE
insert ON CML_SENT_INFOS_HIS_1228 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1228.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1229
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1229 BEFORE
insert ON CML_SENT_INFOS_HIS_1229 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1229.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1230
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1230 BEFORE
insert ON CML_SENT_INFOS_HIS_1230 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1230.nextval into:NEW.I_ID from dual;
end;
/

--TRIG_CML_SENT_INFOS_HIS_1231
CREATE OR REPLACE TRIGGER TRIG_CML_SENT_INFOS_HIS_1231 BEFORE
insert ON CML_SENT_INFOS_HIS_1231 FOR EACH ROW
begin
select SEQ_CML_SENT_INFOS_HIS_1231.nextval into:NEW.I_ID from dual;
end;
/

